### ISSUE TITLE
OCaml 5.4 support

### ISSUE THREAD

**Issue by kit-ty-kate** [pqwy/notty#57]
notty currently fails to build with OCaml 5.4:
```
#=== ERROR while compiling notty.0.2.3 ========================================#
# context              2.4.0~rc1 | linux/x86_64 | ocaml-base-compiler.5.4.0~alpha1 | file:///home/opam/opam-repository
# path                 ~/.opam/5.4/.opam-switch/build/notty.0.2.3
# command              ~/.opam/5.4/bin/dune build -p notty -j 1
# exit-code            1
# env-file             ~/.opam/log/notty-14-670c4a.env
# output-file          ~/.opam/log/notty-14-670c4a.out
### output ###
# (cd _build/default && /home/opam/.opam/5.4/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I src/.notty.objs/byte -I src/.notty.objs/public_cmi -I /home/opam/.opam/5.4/lib/uutf -intf-suffix .ml -no-alias-deps -o src/.notty.objs/byte/notty.cmo -c -impl src/notty.ml)
# File "src/notty.ml", lines 386-396, characters 43-7:
# 386 | ...........................................{
# 387 |           out_flush = (fun () ->
# 388 |             img := !img <-> !line; line := empty; attr := [])
# 389 |         ; out_newline = (fun () ->
# 390 |             img := !img <-> !line; line := void 0 1)
# ...
# 393 |         (* Not entirely clear; either or both could be void: *)
# 394 |         ; out_spaces = (fun w -> line := !line <|> char (top_a attr) ' ' w 1)
# 395 |         ; out_indent = (fun w -> line := !line <|> char (top_a attr) ' ' w 1)
# 396 |       }...
# Error: Some record fields are undefined: out_width
```
